#!/bin/sh

# not set -e: we are testing exit codes

# to have diffoscope able to output stuff in utf-8
export LC_ALL=C.UTF-8

if ! [ -d "$ADTTMP" ]; then
	ADTTMP=`mktemp -d`
	TEMP=true
fi

echo "a" > $ADTTMP/a
echo "a" > $ADTTMP/a_
echo "b" > $ADTTMP/b

echo "Testing identical files..."
diffoscope $ADTTMP/a $ADTTMP/a_
if [ $? -ne 0 ]; then
	echo "Exit code was different from 0 when comparing files with identical content." >&2
	exit 1
fi

echo "Testing different files..."
diffoscope $ADTTMP/a $ADTTMP/b
if [ $? -ne 1 ]; then
	echo "Exit code was different from 1 when comparing files with different content." >&2
	exit 1
fi

echo "Testing LC_ALL=C works"
LC_ALL=C diffoscope --help >/dev/null

echo "Testing invalid command line flag..."
diffoscope --thisflagdoesntexistandwontexist
if [ $? -ne 2 ]; then
	echo "Exit code was different from 2 when passing a non-existent flag." >&2
	exit 1
fi

if [ -n "${TEMP:-}" ]; then
	rm -rf "$ADTTMP"
fi

echo "All good!"
